In [2]:
import pandas as pd
data_fq_A = pd.read_excel('amateur_data_fq_A.xlsx',index_col='index')

In [4]:
data_fq_A.reset_index(inplace=True,drop=True)

In [5]:
data_fq_A

            X_a       Y_a       Z_a        X_ω        Y_ω         Z_ω
0      1.010742 -0.231836 -0.096582  -3.536585   1.097561   -3.963415
1      1.012695 -0.228125 -0.078516  -3.536585   1.097561   -3.963415
2      1.018262 -0.220996 -0.064746  -3.536585   1.097561   -3.963415
3      1.018262 -0.215332 -0.055859  -3.536585   1.097561   -3.963415
4      1.032129 -0.213086 -0.057520  -3.536585   1.097561   -3.963415
...         ...       ...       ...        ...        ...         ...
30595  1.953906 -0.426660 -0.086816 -55.634148  45.292684 -253.682936
30596  1.868945 -0.518652 -0.120898 -34.695122  50.097562 -263.743910
30597  1.727148 -0.588672 -0.156738 -16.219513  50.695124 -264.146348
30598  1.553418 -0.692285 -0.173926 -10.158537  45.463416 -253.097566
30599  1.370898 -0.804199 -0.175684 -18.317073  36.451221 -228.841468

[30600 rows x 6 columns]

In [6]:
data_fq_B_columns=[]
for i in range(50):
    for column in data_fq_A.columns:
        data_fq_B_columns.append(column+'_'+str(i))
print(data_fq_B_columns)

['X_a_0', 'Y_a_0', 'Z_a_0', 'X_ω_0', 'Y_ω_0', 'Z_ω_0', 'X_a_1', 'Y_a_1', 'Z_a_1', 'X_ω_1', 'Y_ω_1', 'Z_ω_1', 'X_a_2', 'Y_a_2', 'Z_a_2', 'X_ω_2', 'Y_ω_2', 'Z_ω_2', 'X_a_3', 'Y_a_3', 'Z_a_3', 'X_ω_3', 'Y_ω_3', 'Z_ω_3', 'X_a_4', 'Y_a_4', 'Z_a_4', 'X_ω_4', 'Y_ω_4', 'Z_ω_4', 'X_a_5', 'Y_a_5', 'Z_a_5', 'X_ω_5', 'Y_ω_5', 'Z_ω_5', 'X_a_6', 'Y_a_6', 'Z_a_6', 'X_ω_6', 'Y_ω_6', 'Z_ω_6', 'X_a_7', 'Y_a_7', 'Z_a_7', 'X_ω_7', 'Y_ω_7', 'Z_ω_7', 'X_a_8', 'Y_a_8', 'Z_a_8', 'X_ω_8', 'Y_ω_8', 'Z_ω_8', 'X_a_9', 'Y_a_9', 'Z_a_9', 'X_ω_9', 'Y_ω_9', 'Z_ω_9', 'X_a_10', 'Y_a_10', 'Z_a_10', 'X_ω_10', 'Y_ω_10', 'Z_ω_10', 'X_a_11', 'Y_a_11', 'Z_a_11', 'X_ω_11', 'Y_ω_11', 'Z_ω_11', 'X_a_12', 'Y_a_12', 'Z_a_12', 'X_ω_12', 'Y_ω_12', 'Z_ω_12', 'X_a_13', 'Y_a_13', 'Z_a_13', 'X_ω_13', 'Y_ω_13', 'Z_ω_13', 'X_a_14', 'Y_a_14', 'Z_a_14', 'X_ω_14', 'Y_ω_14', 'Z_ω_14', 'X_a_15', 'Y_a_15', 'Z_a_15', 'X_ω_15', 'Y_ω_15', 'Z_ω_15', 'X_a_16', 'Y_a_16', 'Z_a_16', 'X_ω_16', 'Y_ω_16', 'Z_ω_16', 'X_a_17', 'Y_a_17', 'Z_a_17', 'X_ω_17', 'Y_ω_17', 'Z_ω_17', 'X_a_18', 'Y_a_18', 'Z_a_18', 'X_ω_18', 'Y_ω_18', 'Z_ω_18', 'X_a_19', 'Y_a_19', 'Z_a_19', 'X_ω_19', 'Y_ω_19', 'Z_ω_19', 'X_a_20', 'Y_a_20', 'Z_a_20', 'X_ω_20', 'Y_ω_20', 'Z_ω_20', 'X_a_21', 'Y_a_21', 'Z_a_21', 'X_ω_21', 'Y_ω_21', 'Z_ω_21', 'X_a_22', 'Y_a_22', 'Z_a_22', 'X_ω_22', 'Y_ω_22', 'Z_ω_22', 'X_a_23', 'Y_a_23', 'Z_a_23', 'X_ω_23', 'Y_ω_23', 'Z_ω_23', 'X_a_24', 'Y_a_24', 'Z_a_24', 'X_ω_24', 'Y_ω_24', 'Z_ω_24', 'X_a_25', 'Y_a_25', 'Z_a_25', 'X_ω_25', 'Y_ω_25', 'Z_ω_25', 'X_a_26', 'Y_a_26', 'Z_a_26', 'X_ω_26', 'Y_ω_26', 'Z_ω_26', 'X_a_27', 'Y_a_27', 'Z_a_27', 'X_ω_27', 'Y_ω_27', 'Z_ω_27', 'X_a_28', 'Y_a_28', 'Z_a_28', 'X_ω_28', 'Y_ω_28', 'Z_ω_28', 'X_a_29', 'Y_a_29', 'Z_a_29', 'X_ω_29', 'Y_ω_29', 'Z_ω_29', 'X_a_30', 'Y_a_30', 'Z_a_30', 'X_ω_30', 'Y_ω_30', 'Z_ω_30', 'X_a_31', 'Y_a_31', 'Z_a_31', 'X_ω_31', 'Y_ω_31', 'Z_ω_31', 'X_a_32', 'Y_a_32', 'Z_a_32', 'X_ω_32', 'Y_ω_32', 'Z_ω_32', 'X_a_33', 'Y_a_33', 'Z_a_33', 'X_ω_33', 'Y_ω_33', 'Z_ω_33', 'X_a_34', 'Y_a_34', 'Z_a_34', 'X_ω_34', 'Y_ω_34', 'Z_ω_34', 'X_a_35', 'Y_a_35', 'Z_a_35', 'X_ω_35', 'Y_ω_35', 'Z_ω_35', 'X_a_36', 'Y_a_36', 'Z_a_36', 'X_ω_36', 'Y_ω_36', 'Z_ω_36', 'X_a_37', 'Y_a_37', 'Z_a_37', 'X_ω_37', 'Y_ω_37', 'Z_ω_37', 'X_a_38', 'Y_a_38', 'Z_a_38', 'X_ω_38', 'Y_ω_38', 'Z_ω_38', 'X_a_39', 'Y_a_39', 'Z_a_39', 'X_ω_39', 'Y_ω_39', 'Z_ω_39', 'X_a_40', 'Y_a_40', 'Z_a_40', 'X_ω_40', 'Y_ω_40', 'Z_ω_40', 'X_a_41', 'Y_a_41', 'Z_a_41', 'X_ω_41', 'Y_ω_41', 'Z_ω_41', 'X_a_42', 'Y_a_42', 'Z_a_42', 'X_ω_42', 'Y_ω_42', 'Z_ω_42', 'X_a_43', 'Y_a_43', 'Z_a_43', 'X_ω_43', 'Y_ω_43', 'Z_ω_43', 'X_a_44', 'Y_a_44', 'Z_a_44', 'X_ω_44', 'Y_ω_44', 'Z_ω_44', 'X_a_45', 'Y_a_45', 'Z_a_45', 'X_ω_45', 'Y_ω_45', 'Z_ω_45', 'X_a_46', 'Y_a_46', 'Z_a_46', 'X_ω_46', 'Y_ω_46', 'Z_ω_46', 'X_a_47', 'Y_a_47', 'Z_a_47', 'X_ω_47', 'Y_ω_47', 'Z_ω_47', 'X_a_48', 'Y_a_48', 'Z_a_48', 'X_ω_48', 'Y_ω_48', 'Z_ω_48', 'X_a_49', 'Y_a_49', 'Z_a_49', 'X_ω_49', 'Y_ω_49', 'Z_ω_49']

In [7]:
data_fq_B=pd.DataFrame(columns=data_fq_B_columns)

In [9]:
data_fq_B

Empty DataFrame
Columns: [X_a_0, Y_a_0, Z_a_0, X_ω_0, Y_ω_0, Z_ω_0, X_a_1, Y_a_1, Z_a_1, X_ω_1, Y_ω_1, Z_ω_1, X_a_2, Y_a_2, Z_a_2, X_ω_2, Y_ω_2, Z_ω_2, X_a_3, Y_a_3, Z_a_3, X_ω_3, Y_ω_3, Z_ω_3, X_a_4, Y_a_4, Z_a_4, X_ω_4, Y_ω_4, Z_ω_4, X_a_5, Y_a_5, Z_a_5, X_ω_5, Y_ω_5, Z_ω_5, X_a_6, Y_a_6, Z_a_6, X_ω_6, Y_ω_6, Z_ω_6, X_a_7, Y_a_7, Z_a_7, X_ω_7, Y_ω_7, Z_ω_7, X_a_8, Y_a_8, Z_a_8, X_ω_8, Y_ω_8, Z_ω_8, X_a_9, Y_a_9, Z_a_9, X_ω_9, Y_ω_9, Z_ω_9, X_a_10, Y_a_10, Z_a_10, X_ω_10, Y_ω_10, Z_ω_10, X_a_11, Y_a_11, Z_a_11, X_ω_11, Y_ω_11, Z_ω_11, X_a_12, Y_a_12, Z_a_12, X_ω_12, Y_ω_12, Z_ω_12, X_a_13, Y_a_13, Z_a_13, X_ω_13, Y_ω_13, Z_ω_13, X_a_14, Y_a_14, Z_a_14, X_ω_14, Y_ω_14, Z_ω_14, X_a_15, Y_a_15, Z_a_15, X_ω_15, Y_ω_15, Z_ω_15, X_a_16, Y_a_16, Z_a_16, X_ω_16, ...]
Index: []

[0 rows x 300 columns]

In [10]:
for i in range(int(len(data_fq_A)/50)):
    data_columns = []
    for j in range(50):
        data_columns.extend(list(data_fq_A.loc[i*50+j]))
    data_fq_B.loc[i] = data_columns
    data_columns.clear()

In [11]:
data_fq_B

,X_a_0,Y_a_0,Z_a_0,X_ω_0,Y_ω_0,Z_ω_0,X_a_1,Y_a_1,Z_a_1,X_ω_1,...,Z_a_48,X_ω_48,Y_ω_48,Z_ω_48,X_a_49,Y_a_49,Z_a_49,X_ω_49,Y_ω_49,Z_ω_49
0,1.010742,-0.231836,-0.096582,-3.536585,1.097561,-3.963415,1.012695,-0.228125,-0.078516,-3.536585,...,-0.316406,6.500000,-40.817074,-295.865868,1.577441,-4.710254,-0.298633,-22.536586,-41.256098,-177.475627
1,1.034863,-0.233887,0.043066,-0.304878,2.439024,-3.231707,1.031445,-0.243359,0.039258,-0.304878,...,-0.180762,-55.121957,28.256098,-483.780492,3.895215,-2.012109,-0.131055,-49.426835,2.012194,-367.524397
2,1.027148,-0.191699,-0.008008,7.195122,-1.780488,6.987805,1.022168,-0.201953,-0.014355,14.487805,...,0.204785,75.390244,46.182928,-507.853674,2.660059,-2.712305,-0.205566,22.243903,20.341464,-416.451233
3,1.024121,-0.265137,-0.054297,10.085366,3.426829,17.890245,1.026074,-0.274121,-0.051562,9.390244,...,0.054980,-10.365854,28.756099,-357.036592,3.766309,-3.788476,0.224609,4.463416,1.951220,-226.170736
4,1.019238,-0.225098,-0.059277,0.000000,0.731707,-4.085366,1.020898,-0.225781,-0.059180,0.000000,...,-0.636426,-63.512195,-5.768293,-302.304883,1.770313,-3.688769,-0.629004,-68.853660,-18.987806,-212.707319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,1.008789,-0.175000,-0.138965,2.195122,0.304878,1.219512,1.012500,-0.172168,-0.134863,2.195122,...,-0.364941,-31.280489,70.048783,-186.756102,1.739648,-0.516895,-0.391797,-33.963416,62.670734,-175.097566
608,1.012305,-0.169727,-0.162207,-2.317073,-1.829268,4.024390,1.014746,-0.182520,-0.168066,-2.317073,...,-0.364941,-31.280489,70.048783,-186.756102,1.739648,-0.516895,-0.391797,-33.963416,62.670734,-175.097566
609,1.018652,-0.230273,-0.105566,3.719512,1.402439,2.560976,1.019434,-0.227539,-0.102539,3.719512,...,-0.449316,-81.073172,72.439026,-151.317077,1.307813,-0.590430,-0.509766,-86.926831,66.097562,-132.158541
610,1.019434,-0.162402,-0.118164,-0.500000,5.439024,12.304878,1.019922,-0.173242,-0.116895,0.256098,...,-0.277930,-88.402443,46.536586,-117.890248,1.457812,-0.335840,-0.318652,-96.073175,43.670732,-106.341466
611,1.013965,-0.200488,-0.145703,0.682927,5.707317,4.414634,1.014063,-0.200488,-0.147656,0.768293,...,-0.173926,-10.158537,45.463416,-253.097566,1.370898,-0.804199,-0.175684,-18.317073,36.451221,-228.841468

In [12]:
data_fq_B_T = pd.DataFrame(data_fq_B.values.T, index=data_fq_B.columns, columns=data_fq_B.index)#转置

In [13]:
data_fq_B_T

,0,1,2,3,4,5,6,7,8,9,...,602,603,604,605,606,607,608,609,610,611
X_a_0,1.010742,1.034863,1.027148,1.024121,1.019238,1.029688,1.021680,1.002637,1.015430,0.973437,...,1.024707,1.016406,1.011914,1.001465,1.020410,1.008789,1.012305,1.018652,1.019434,1.013965
Y_a_0,-0.231836,-0.233887,-0.191699,-0.265137,-0.225098,-0.159180,-0.255566,0.060742,-0.019336,0.077148,...,-0.179492,-0.266602,-0.208203,-0.246191,-0.122949,-0.175000,-0.169727,-0.230273,-0.162402,-0.200488
Z_a_0,-0.096582,0.043066,-0.008008,-0.054297,-0.059277,-0.015430,-0.008496,0.071289,0.075391,0.027441,...,-0.124316,-0.136328,-0.114062,-0.136133,-0.131836,-0.138965,-0.162207,-0.105566,-0.118164,-0.145703
X_ω_0,-3.536585,-0.304878,7.195122,10.085366,0.000000,-1.609756,-3.207317,0.292683,2.219512,3.024390,...,-0.646341,1.829268,-2.317073,4.268293,3.439024,2.195122,-2.317073,3.719512,-0.500000,0.682927
Y_ω_0,1.097561,2.439024,-1.780488,3.426829,0.731707,4.658537,2.243903,5.829268,-1.304878,1.182927,...,11.792683,6.402439,2.317073,-0.304878,5.195122,0.304878,-1.829268,1.402439,5.439024,5.707317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Y_a_49,-4.710254,-2.012109,-2.712305,-3.788476,-3.688769,-0.912207,-1.293457,-3.311133,-0.978516,-1.780859,...,-1.106738,-0.807617,-0.511426,-0.685937,-0.621484,-0.516895,-0.516895,-0.590430,-0.335840,-0.804199
Z_a_49,-0.298633,-0.131055,-0.205566,0.224609,-0.629004,0.016406,0.079395,-0.644727,0.160937,-0.525391,...,-0.373242,-0.505176,-0.281445,-0.496387,-0.540332,-0.391797,-0.391797,-0.509766,-0.318652,-0.175684
X_ω_49,-22.536586,-49.426835,22.243903,4.463416,-68.853660,-12.426830,108.536586,-1.317072,95.804875,-38.829269,...,-23.621952,-100.695123,-83.195123,-103.536587,-108.304878,-33.963416,-33.963416,-86.926831,-96.073175,-18.317073
Y_ω_49,-41.256098,2.012194,20.341464,1.951220,-18.987806,-12.829268,39.268294,11.182927,-16.365853,-38.475611,...,1.451220,46.158539,30.500000,52.109757,74.182929,62.670734,62.670734,66.097562,43.670732,36.451221
Z_ω_49,-177.475627,-367.524397,-416.451233,-226.170736,-212.707319,-359.353668,-455.719534,-295.243912,-428.731712,-172.365855,...,-71.060977,-124.426836,-128.256101,-197.695130,-137.890248,-175.097566,-175.097566,-132.158541,-106.341466,-228.841468

In [15]:
data_fq_B_T.to_excel('amateur_data_fq_B_T.xlsx')